import React, { useEffect, useRef, useState } from "react";
import axios from "axios";
import { Html5Qrcode } from "html5-qrcode";
import { useNavigate } from "react-router-dom";

const ScanQRCode = () => {
  const [student, setStudent] = useState(null);
  const [status, setStatus] = useState("ready");
  const [showReceipt, setShowReceipt] = useState(false);
  const [mps, setMps] = useState(0);
  const [scanHistory, setScanHistory] = useState([]);

  const [cameras, setCameras] = useState([]);
  const [selectedCam, setSelectedCam] = useState(null);
  const [scanner, setScanner] = useState(null);
  const [isCameraActive, setIsCameraActive] = useState(true);

  const scannerRef = useRef(null);
  const navigate = useNavigate();

  // SOUND
  const playBeep = (type = "success") => {
    const ctx = new (window.AudioContext || window.webkitAudioContext)();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();

    osc.type = "sine";
    osc.frequency.value = type === "success" ? 800 : 200;

    gain.gain.value = 0.08;

    osc.connect(gain);
    gain.connect(ctx.destination);

    osc.start();
    osc.stop(ctx.currentTime + 0.15);
  };

  //  FAKE METRICS
  useEffect(() => {
    const interval = setInterval(() => {
      setMps((p) => Math.min(120, p + Math.floor(Math.random() * 3)));
    }, 2000);

    return () => clearInterval(interval);
  }, []);

  // INIT CAMERA LIST
  useEffect(() => {
    Html5Qrcode.getCameras()
      .then((devices) => {
        setCameras(devices);
        if (devices?.length) setSelectedCam(devices[0].id);
      })
      .catch(() => {});
  }, []);

  // START SCANNER
  useEffect(() => {
    if (!selectedCam || !isCameraActive) {
      setStatus("off");
      setScanner(null);
      return;
    }

    const qr = new Html5Qrcode("reader");
    setScanner(qr);

    setStatus("scanning");

    qr.start(
      selectedCam,
      {
        fps: 10,
        qrbox: { width: 250, height: 250 },
      },
      (decodedText) => {async (decodedText) => {
  try {
    qr.pause(true);

    const userInfo = JSON.parse(
      localStorage.getItem("userInfo")
    );

    const config = {
      headers: {
        Authorization: `Bearer ${userInfo.token}`,
      },
    };

    const { data } = await axios.post(
      "http://localhost:5000/api/qr/validate",
      {
        token: decodedText,
      },
      config
    );

    const studentData = {
      name: data.studentName,
      id: data.studentId,
      credits: data.remainingCredits,
      major: data.major || "Student",
      photo: data.photo || null,
    };

    setStudent(studentData);

    playBeep("success");
    setStatus("success");
    setShowReceipt(true);

    setScanHistory((prev) => [
      {
        ...studentData,
        status: "success",
        time: new Date().toLocaleTimeString(),
      },
      ...prev,
    ].slice(0, 10));

    setTimeout(() => {
      setShowReceipt(false);
      setStatus("scanning");
      qr.resume();
    }, 3000);
  } catch (error) {
    console.error(error);

    playBeep("error");
    setStatus("error");

    const historyItem = {
      name: "Invalid QR",
      id: "N/A",
      credits: 0,
      major: "N/A",
      status: "error",
      time: new Date().toLocaleTimeString(),
    };

    setStudent(historyItem);

    setScanHistory((prev) => [
      historyItem,
      ...prev,
    ].slice(0, 10));

    setTimeout(() => {
      setStatus("scanning");
      qr.resume();
    }, 3000);
  }
}
        console.log(decodedText);

        let scanResult = "success";
        let studentData;
        try {
          // Try parsing JSON if QR was generated by our test tool
          const parsed = JSON.parse(decodedText);
          studentData = {
            name: parsed.name || "Test Student",
            id: parsed.id || "TEST-ID",
            credits: parsed.credits !== undefined ? Number(parsed.credits) : 0,
            major: parsed.major || "Testing Dept",
            photo: parsed.photo || null
          };
        } catch (e) {
          // Fallback to original random mock data for plain text IDs
          studentData = {
            name: `Student ${decodedText}`,
            id: decodedText,
            credits: Math.random() > 0.2 ? 10 : 0,
            major: "General Studies",
            photo: null
          };
        }

        if (studentData.credits <= 0) {
          setStudent(studentData);
          scanResult = "error";
          playBeep("error");
          setStatus("error");
          setTimeout(() => setStatus("scanning"), 2000);
        } else {
          // Deduct exactly 1 credit logic
          studentData.credits -= 1;
          setStudent(studentData);

          playBeep("success");
          setStatus("success");
          setShowReceipt(true);

          setTimeout(() => {
            setShowReceipt(false);
            setStatus("scanning");
          }, 3000);
        }

        // Add to history
        const historyItem = {
          ...studentData,
          status: scanResult,
          time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
        };
        setScanHistory(prev => [historyItem, ...prev].slice(0, 10));
      }
    );

    return () => {
      qr.stop().then(() => qr.clear()).catch(() => {});
    };
  }, [selectedCam, isCameraActive]);

  const resetScanner = () => {
    setStudent(null);
    setStatus("ready");
  };

  const handleLogout = () => {
    localStorage.removeItem("userInfo");
    navigate("/");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#F8FAFC] to-[#ECFDF5] flex flex-col">

      {/* HEADER */}
      <header className="bg-white border-b px-4 sm:px-6 py-4 flex justify-between items-center shadow-sm sticky top-0 z-50">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 sm:w-11 sm:h-11 bg-[#15803D] rounded-xl sm:rounded-2xl flex items-center justify-center text-white font-bold">
            R
          </div>

          <div>
            <h1 className="text-base sm:text-lg font-black text-[#15803D] leading-tight">
              Restau Scanner Pro
            </h1>
            <p className="text-[9px] sm:text-[10px] uppercase tracking-widest text-gray-400">
              Dining Terminal • Live System
            </p>
          </div>
        </div>

        <button
          onClick={handleLogout}
          className="px-3 py-1.5 sm:px-4 sm:py-2 bg-gray-100 hover:bg-red-50 text-gray-600 hover:text-red-600 rounded-full text-[10px] sm:text-xs font-bold transition-colors"
        >
          Logout
        </button>
      </header>

      <main className="flex-1 p-4 sm:p-6 lg:p-10 max-w-6xl mx-auto w-full space-y-6 sm:space-y-8">

        {/* TOP STATUS */}
        <div className="bg-gradient-to-r from-[#15803D] to-green-700 text-white p-5 sm:p-6 rounded-[2rem] shadow-lg">
          <div className="flex flex-row justify-between items-center gap-4">
            <div>
              <h2 className="text-lg sm:text-xl font-bold">Live Scanner Active</h2>
              <p className="text-xs sm:text-sm opacity-80">QR authentication running</p>
            </div>

            <div className="bg-white/20 px-3 py-1 sm:px-4 sm:py-2 rounded-full text-[10px] sm:text-xs font-bold whitespace-nowrap">
              {status.toUpperCase()}
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-5 gap-6 sm:gap-8">

          {/* SCANNER */}
          <div className="lg:col-span-3 bg-white p-4 sm:p-6 rounded-[2rem] shadow-xl border border-[#DCFCE7]">

            <div className="flex flex-wrap justify-between items-center gap-3 mb-4">

              <h3 className="font-bold text-[#15803D] flex items-center gap-2">
                📷 QR Scanner
              </h3>

              <div className="flex items-center gap-2">
                {/* CAMERA DROPDOWN */}
                <select
                  className="text-[10px] sm:text-xs border px-2 py-1.5 sm:px-3 sm:py-2 rounded-xl bg-white shadow-sm outline-none focus:ring-1 focus:ring-green-600"
                  value={selectedCam || ""}
                  onChange={(e) => setSelectedCam(e.target.value)}
                >
                  {cameras.map((cam) => (
                    <option key={cam.id} value={cam.id}>
                      {cam.label || "Camera"}
                    </option>
                  ))}
                </select>

                {/* CAMERA TOGGLE */}
                <button
                  onClick={() => setIsCameraActive(!isCameraActive)}
                  className={`text-[10px] sm:text-xs px-2 py-1.5 sm:px-3 sm:py-2 rounded-xl transition-all font-bold border ${
                    isCameraActive 
                      ? "bg-green-100 text-green-700 border-green-200 hover:bg-green-200" 
                      : "bg-red-100 text-red-700 border-red-200 hover:bg-red-200"
                  }`}
                >
                  {isCameraActive ? "📷 Camera On" : "📷 Camera Off"}
                </button>
              </div>

            </div>

            {/* SCANNER BOX */}
            <div className="rounded-2xl sm:rounded-[2rem] overflow-hidden border-4 border-[#15803D] bg-black shadow-2xl aspect-square sm:aspect-auto">
              <div id="reader" ref={scannerRef}></div>
            </div>

          </div>

          {/* STUDENT PANEL */}
          <div className={`lg:col-span-2 bg-white p-5 sm:p-6 rounded-[2rem] shadow-xl border transition-all duration-300 ${
            status === "error" ? "border-red-400 ring-4 ring-red-50" : status === "success" ? "border-green-400 ring-4 ring-green-50" : "border-[#DCFCE7]"
          }`}>
            
            {!student ? (
              <div className="text-center py-12 sm:py-16 text-gray-400">
                <div className="w-16 h-16 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-4 border-2 border-dashed border-gray-200 overflow-hidden">
                   <img src="https://ui-avatars.com/api/?name=User&background=f8fafc&color=cbd5e1&bold=true" className="w-full h-full object-cover opacity-50" alt="User" />
                </div>
                <p className="font-bold text-sm sm:text-base">Waiting for scan...</p>
                <p className="text-xs mt-1">Place QR code in frame</p>
              </div>
            ) : (
              <div>
                {/* Result Indicator */}
                <div className={`mb-6 p-4 rounded-2xl flex items-center justify-center gap-2 font-black text-sm uppercase tracking-widest ${
                  status === "error" ? "bg-red-100 text-red-600 animate-pulse" : "bg-green-100 text-green-600"
                }`}>
                  {status === "error" ? "❌ Rejected" : "✅ Approved"}
                </div>

                <div className="text-center mb-6">
                  <div className={`w-16 h-16 sm:w-20 sm:h-20 rounded-full mx-auto mb-3 flex items-center justify-center border-4 overflow-hidden shadow-inner ${status === 'error' ? 'bg-red-50 border-red-100 text-red-400' : 'bg-green-50 border-green-100 text-green-600'}`}>
                    {student.photo ? (
                       <img src={student.photo} alt={student.name} className="w-full h-full object-cover" />
                    ) : (
                       <img src={`https://ui-avatars.com/api/?name=${encodeURIComponent(student.name)}&background=${status === 'error' ? 'fef2f2' : 'f0fdf4'}&color=${status === 'error' ? 'b91c1c' : '166534'}&bold=true`} alt={student.name} className="w-full h-full object-cover" />
                    )}
                  </div>
                  <h3 className="text-xl font-black text-gray-800">
                    {student.name}
                  </h3>
                  <p className="text-[10px] sm:text-xs text-gray-500 font-bold uppercase tracking-tight">{student.major}</p>
                </div>

                <div className="mt-4 p-4 bg-gray-50 rounded-xl sm:rounded-2xl space-y-3">
                  <div className="flex justify-between items-center text-xs">
                    <span className="text-gray-400 font-bold uppercase">Matricule</span>
                    <span className="font-mono font-bold text-gray-700">{student.id}</span>
                  </div>

                  <div className="flex justify-between items-center text-xs">
                    <span className="text-gray-400 font-bold uppercase">Meal Credits</span>
                    <span className={`font-black text-sm ${student.credits > 0 ? 'text-green-600' : 'text-red-500'}`}>
                      {student.credits}
                    </span>
                  </div>
                </div>

                <button
                  onClick={resetScanner}
                  className="w-full mt-6 py-3 sm:py-4 bg-gray-900 hover:bg-black text-white rounded-xl sm:rounded-2xl font-bold transition-all shadow-lg active:scale-95 text-sm"
                >
                  Clear Results
                </button>

              </div>
            )}
          </div>
        </div>

        {/* SCAN HISTORY */}
        <div className="bg-white p-5 sm:p-8 rounded-[2rem] sm:rounded-[2.5rem] shadow-sm border border-gray-100">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-6 gap-2">
            <h3 className="text-xl font-bold text-green-900 flex items-center gap-2">
              Recent Scans
            </h3>
            <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Last 10 scans</span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead className="bg-gray-50/50 text-gray-400 text-[10px] uppercase font-black tracking-widest">
                <tr>
                  <th className="px-4 sm:px-6 py-4">Student</th>
                  <th className="px-4 sm:px-6 py-4">Time</th>
                  <th className="px-4 sm:px-6 py-4 hidden sm:table-cell">Details</th>
                  <th className="px-4 sm:px-6 py-4 text-right">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {scanHistory.length === 0 ? (
                  <tr>
                    <td colSpan="4" className="px-6 py-8 text-center text-gray-400 text-sm">No activity recorded yet. Start scanning to see results here.</td>
                  </tr>
                ) : (
                  scanHistory.map((item, index) => (
                    <tr key={index} className="hover:bg-gray-50/50 transition-colors">
                      <td className="px-4 sm:px-6 py-4">
                        <div className="flex items-center gap-3">
                          <div className="w-8 h-8 rounded-full overflow-hidden border border-gray-100 bg-gray-50 flex-shrink-0">
                             <img src={item.photo || `https://ui-avatars.com/api/?name=${encodeURIComponent(item.name)}&background=f8fafc&color=64748b&bold=true`} alt={item.name} className="w-full h-full object-cover" />
                          </div>
                          <div className="font-bold text-gray-800 text-sm">{item.name}</div>
                          <div className="sm:hidden text-[9px] text-gray-400 uppercase font-medium">{item.id}</div>
                        </div>
                      </td>
                      <td className="px-4 sm:px-6 py-4 text-xs sm:text-sm text-gray-500">{item.time}</td>
                      <td className="px-4 sm:px-6 py-4 text-[10px] text-gray-400 font-medium uppercase hidden sm:table-cell">
                        {item.id} • {item.major}
                      </td>
                      <td className="px-4 sm:px-6 py-4 text-right">
                        <span className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase ${
                          item.status === 'success' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                        }`}>
                          {item.status === 'success' ? 'Success' : 'Rejected'}
                        </span>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* STATS */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-6">

          <div className="bg-white p-5 sm:p-6 rounded-2xl sm:rounded-3xl shadow-sm border border-gray-50">
            <p className="text-xs text-gray-400">Meals/min</p>
            <h3 className="text-2xl sm:text-3xl font-black text-[#15803D]">{mps}</h3>
          </div>

          <div className="bg-white p-5 sm:p-6 rounded-2xl sm:rounded-3xl shadow-sm border border-gray-50">
            <p className="text-xs text-gray-400">Revenue</p>
            <h3 className="text-2xl sm:text-3xl font-black text-[#15803D]">54,100</h3>
          </div>

          <div className="bg-white p-5 sm:p-6 rounded-2xl sm:rounded-3xl shadow-sm border border-gray-50">
            <p className="text-xs text-gray-400">Efficiency</p>
            <h3 className="text-2xl sm:text-3xl font-black text-[#16A34A]">92%</h3>
          </div>

        </div>

      </main>

      {/* RECEIPT */}
      {showReceipt && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center">
          <div className="bg-white p-6 rounded-3xl shadow-xl w-[280px] text-center">
            <h3 className="font-bold text-[#15803D]">Receipt</h3>
            <p className="text-sm mt-2">{student?.name}</p>
            <p className="text-xs text-gray-500 mt-2">Access Granted ✔</p>
          </div>
        </div>
      )}

    </div>
  );
};

export default ScanQRCode;